=== rrazvanrraducanu/XML0/data.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="uaic">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element type="xs:string" name="title"/>
        <xs:element type="xs:string" name="msg1"/>
        <xs:element type="xs:string" name="name"/>
        <xs:element type="xs:string" name="emphasis"/>
        <xs:element type="xs:string" name="msg2"/>
        <xs:element type="xs:string" name="msg3"/>
        <xs:element name="image">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="img">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:byte" name="width"/>
                      <xs:attribute type="xs:byte" name="height"/>
                      <xs:attribute type="xs:string" name="alt"/>
                      <xs:attribute type="xs:string" name="src"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== rrazvanrraducanu/XML0/data.xml
<?xml version="1.0"?>

<?xml-stylesheet type="text/xsl" href="data.xsl"?>
<uaic xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="data.xsd">
   <title>UAIC welcome message</title>

   <msg1>Welcome to</msg1> 
   <name> UAIC</name>, 
   <emphasis> the oldest university</emphasis> 
   <msg2> in Romania!</msg2>

   <msg3>UAIC LOGO: </msg3> 
    <image>
        <img width="100" height="100" alt="bla bla" src="images/uaic.jpg"/>
    </image>

</uaic>
